[project]
name = "barebells"
version = "0.1.0"
description = "Barebells tracker"
channels = ["pytorch", "conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = ">=3.11"
requests = "*"
beautifulsoup4 = "*"
lxml = "*"  # Faster parser for BeautifulSoup
urllib3 = "*"
certifi = "*"  # For HTTPS certificate verification
chardet = "*"  # For character encoding detection
idna = "*"     # For international domain names
soupsieve = "*"  # CSS selector support for BeautifulSoup
regex = "*"    # More powerful regular expressions
typing-extensions = "*"

